### ISSUE TITLE
Crear pantalla de landing (inicio)

### ISSUE THREAD

**Issue by JoseVCS** [TeamSalus/Proyecto_Pedidos#1]
Se pide una pantalla de entrada de demostración que mostrará un acceso a login, una seleccion basica de productos, un mapa (futuro Google maps) y un formulario de contacto. Ademas se añade un menu en la zona superior. Las funcionalidades (acceso BD, registros...) no se implementan. Se desea una base inicial solo funcional a nivel visual (IU)

**Comment by ratarcs** [comment]
Realizado y subido
